export interface FinancialRatioField {
  field: string;
  displayName: string;
  description: string;
  category: string;
  tool: string;
  keywords: string[];
  unit?: string;
  isRatio?: boolean;
  isPercentage?: boolean;
}

export const financialRatiosFields: FinancialRatioField[] = [
  // Profitability Ratios
  {
    field: 'grossProfitMargin',
    displayName: 'Gross Profit Margin',
    description: 'Percentage of revenue retained after deducting cost of goods sold',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['gross profit', 'margin', 'profitability', 'revenue', 'cogs', '毛利率', '收入', '成本'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'ebitMargin',
    displayName: 'EBIT Margin',
    description: 'Earnings before interest and taxes as a percentage of revenue',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['ebit', 'margin', 'operating profit', 'earnings', '息税前利润率', '营业利润'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'ebitdaMargin',
    displayName: 'EBITDA Margin',
    description: 'Earnings before interest, taxes, depreciation and amortization as a percentage of revenue',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['ebitda', 'margin', 'cash earnings', 'depreciation', '息税折旧摊销前利润率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'operatingProfitMargin',
    displayName: 'Operating Profit Margin',
    description: 'Operating income as a percentage of revenue',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['operating margin', 'operating profit', 'operational efficiency', '营业利润率', '运营效率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'pretaxProfitMargin',
    displayName: 'Pre-tax Profit Margin',
    description: 'Earnings before taxes as a percentage of revenue',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['pretax margin', 'profit before tax', 'ebt margin', '税前利润率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'netProfitMargin',
    displayName: 'Net Profit Margin',
    description: 'Net income as a percentage of revenue, showing overall profitability',
    category: 'Profitability Ratios',
    tool: 'getFinancialRatios',
    keywords: ['net margin', 'profit margin', 'bottom line', 'net income', '净利润率', '净利率'],
    isRatio: true,
    isPercentage: true,
  },

  // Efficiency Ratios
  {
    field: 'receivablesTurnover',
    displayName: 'Receivables Turnover',
    description: 'How many times per year a company collects its average accounts receivable',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['receivables', 'turnover', 'collection', 'accounts receivable', '应收账款周转率', '收款效率'],
    isRatio: true,
  },
  {
    field: 'payablesTurnover',
    displayName: 'Payables Turnover',
    description: 'How many times per year a company pays its average accounts payable',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['payables', 'turnover', 'payment', 'accounts payable', '应付账款周转率', '付款效率'],
    isRatio: true,
  },
  {
    field: 'inventoryTurnover',
    displayName: 'Inventory Turnover',
    description: 'How many times per year inventory is sold and replaced',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['inventory', 'turnover', 'stock rotation', 'inventory management', '存货周转率', '库存效率'],
    isRatio: true,
  },
  {
    field: 'fixedAssetTurnover',
    displayName: 'Fixed Asset Turnover',
    description: 'Revenue generated per dollar of fixed assets',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['fixed assets', 'turnover', 'asset efficiency', 'capital efficiency', '固定资产周转率'],
    isRatio: true,
  },
  {
    field: 'assetTurnover',
    displayName: 'Asset Turnover',
    description: 'Revenue generated per dollar of total assets',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['asset turnover', 'total assets', 'efficiency', 'asset utilization', '总资产周转率', '资产利用率'],
    isRatio: true,
  },

  // Liquidity Ratios
  {
    field: 'currentRatio',
    displayName: 'Current Ratio',
    description: 'Current assets divided by current liabilities, measuring short-term liquidity',
    category: 'Liquidity Ratios',
    tool: 'getFinancialRatios',
    keywords: ['current ratio', 'liquidity', 'working capital', 'short-term solvency', '流动比率', '短期偿债能力'],
    isRatio: true,
  },
  {
    field: 'quickRatio',
    displayName: 'Quick Ratio',
    description: 'Quick assets divided by current liabilities, a more conservative liquidity measure',
    category: 'Liquidity Ratios',
    tool: 'getFinancialRatios',
    keywords: ['quick ratio', 'acid test', 'liquid assets', 'immediate liquidity', '速动比率', '酸性测试比率'],
    isRatio: true,
  },
  {
    field: 'cashRatio',
    displayName: 'Cash Ratio',
    description: 'Cash and cash equivalents divided by current liabilities',
    category: 'Liquidity Ratios',
    tool: 'getFinancialRatios',
    keywords: ['cash ratio', 'cash liquidity', 'cash coverage', 'absolute liquidity', '现金比率', '现金流动性'],
    isRatio: true,
  },

  // Valuation Ratios
  {
    field: 'priceToEarningsRatio',
    displayName: 'P/E Ratio',
    description: 'Stock price relative to earnings per share',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['PE ratio', 'price earnings', 'valuation multiple', 'earnings multiple', '市盈率', '估值倍数'],
    isRatio: true,
  },
  {
    field: 'priceToEarningsGrowthRatio',
    displayName: 'PEG Ratio',
    description: 'P/E ratio divided by earnings growth rate',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['PEG ratio', 'growth adjusted PE', 'valuation growth', '市盈率增长比', 'PEG'],
    isRatio: true,
  },
  {
    field: 'priceToBookRatio',
    displayName: 'P/B Ratio',
    description: 'Market value relative to book value',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['PB ratio', 'price book', 'book value multiple', 'market to book', '市净率', '账面价值'],
    isRatio: true,
  },
  {
    field: 'priceToSalesRatio',
    displayName: 'P/S Ratio',
    description: 'Market cap divided by revenue',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['PS ratio', 'price sales', 'revenue multiple', 'sales multiple', '市销率', '销售倍数'],
    isRatio: true,
  },
  {
    field: 'priceToFreeCashFlowRatio',
    displayName: 'P/FCF Ratio',
    description: 'Market cap divided by free cash flow',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['price to FCF', 'free cash flow multiple', 'FCF valuation', '市价自由现金流比率'],
    isRatio: true,
  },
  {
    field: 'priceToOperatingCashFlowRatio',
    displayName: 'P/OCF Ratio',
    description: 'Market cap divided by operating cash flow',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['price to OCF', 'operating cash flow multiple', 'OCF valuation', '市价运营现金流比率'],
    isRatio: true,
  },
  {
    field: 'enterpriseValueMultiple',
    displayName: 'EV/EBITDA',
    description: 'Enterprise value divided by EBITDA',
    category: 'Valuation Ratios',
    tool: 'getFinancialRatios',
    keywords: ['EV multiple', 'enterprise value', 'EBITDA multiple', 'EV/EBITDA', '企业价值倍数'],
    isRatio: true,
  },

  // Leverage Ratios
  {
    field: 'debtToAssetsRatio',
    displayName: 'Debt to Assets',
    description: 'Total debt as a percentage of total assets',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['debt to assets', 'leverage', 'debt ratio', 'financial leverage', '资产负债率', '债务比率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'debtToEquityRatio',
    displayName: 'Debt to Equity',
    description: 'Total debt divided by total equity',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['debt to equity', 'D/E ratio', 'leverage ratio', 'gearing', '债务权益比', '杠杆率'],
    isRatio: true,
  },
  {
    field: 'debtToCapitalRatio',
    displayName: 'Debt to Capital',
    description: 'Total debt as a percentage of total capital',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['debt to capital', 'capital structure', 'debt percentage', '债务资本比率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'longTermDebtToCapitalRatio',
    displayName: 'Long-term Debt to Capital',
    description: 'Long-term debt as a percentage of total capital',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['long term debt', 'capital structure', 'LT debt ratio', '长期债务资本比率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'financialLeverageRatio',
    displayName: 'Financial Leverage',
    description: 'Total assets divided by total equity',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['financial leverage', 'equity multiplier', 'leverage factor', '财务杠杆', '权益乘数'],
    isRatio: true,
  },

  // Cash Flow Ratios
  {
    field: 'operatingCashFlowRatio',
    displayName: 'Operating Cash Flow Ratio',
    description: 'Operating cash flow divided by current liabilities',
    category: 'Cash Flow Ratios',
    tool: 'getFinancialRatios',
    keywords: ['OCF ratio', 'cash flow coverage', 'operating cash', '运营现金流比率'],
    isRatio: true,
  },
  {
    field: 'operatingCashFlowSalesRatio',
    displayName: 'OCF to Sales Ratio',
    description: 'Operating cash flow as a percentage of sales',
    category: 'Cash Flow Ratios',
    tool: 'getFinancialRatios',
    keywords: ['cash flow margin', 'OCF sales', 'cash generation', '现金流销售比率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'freeCashFlowOperatingCashFlowRatio',
    displayName: 'FCF/OCF Ratio',
    description: 'Free cash flow as a percentage of operating cash flow',
    category: 'Cash Flow Ratios',
    tool: 'getFinancialRatios',
    keywords: ['FCF ratio', 'free cash conversion', 'cash efficiency', '自由现金流转换率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'capitalExpenditureCoverageRatio',
    displayName: 'CapEx Coverage Ratio',
    description: 'Operating cash flow divided by capital expenditures',
    category: 'Cash Flow Ratios',
    tool: 'getFinancialRatios',
    keywords: ['capex coverage', 'capital spending', 'investment coverage', '资本支出覆盖率'],
    isRatio: true,
  },

  // Coverage Ratios
  {
    field: 'interestCoverageRatio',
    displayName: 'Interest Coverage Ratio',
    description: 'EBIT divided by interest expense',
    category: 'Coverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['interest coverage', 'times interest earned', 'debt service', '利息保障倍数'],
    isRatio: true,
  },
  {
    field: 'debtServiceCoverageRatio',
    displayName: 'Debt Service Coverage Ratio',
    description: 'Net operating income divided by total debt service',
    category: 'Coverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['DSCR', 'debt service', 'debt coverage', '债务偿还覆盖率'],
    isRatio: true,
  },
  {
    field: 'dividendPaidAndCapexCoverageRatio',
    displayName: 'Dividend & CapEx Coverage',
    description: 'Cash flow coverage for dividends and capital expenditures',
    category: 'Coverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['dividend coverage', 'capex coverage', 'cash allocation', '股息资本支出覆盖率'],
    isRatio: true,
  },

  // Dividend Ratios
  {
    field: 'dividendPayoutRatio',
    displayName: 'Dividend Payout Ratio',
    description: 'Percentage of earnings paid out as dividends',
    category: 'Dividend Ratios',
    tool: 'getFinancialRatios',
    keywords: ['payout ratio', 'dividend payout', 'earnings distribution', '股息支付率', '派息率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'dividendYield',
    displayName: 'Dividend Yield',
    description: 'Annual dividends per share divided by stock price',
    category: 'Dividend Ratios',
    tool: 'getFinancialRatios',
    keywords: ['dividend yield', 'yield', 'income return', '股息率', '股息收益率'],
    isRatio: true,
  },
  {
    field: 'dividendYieldPercentage',
    displayName: 'Dividend Yield %',
    description: 'Dividend yield expressed as a percentage',
    category: 'Dividend Ratios',
    tool: 'getFinancialRatios',
    keywords: ['dividend yield percentage', 'yield percent', '股息率百分比'],
    isRatio: true,
    isPercentage: true,
  },

  // Per Share Metrics
  {
    field: 'revenuePerShare',
    displayName: 'Revenue Per Share',
    description: 'Total revenue divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['revenue per share', 'RPS', 'sales per share', '每股收入', '每股销售额'],
    unit: 'USD',
  },
  {
    field: 'netIncomePerShare',
    displayName: 'Net Income Per Share',
    description: 'Net income divided by shares outstanding (EPS)',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['EPS', 'earnings per share', 'net income per share', '每股收益', '每股净利润'],
    unit: 'USD',
  },
  {
    field: 'cashPerShare',
    displayName: 'Cash Per Share',
    description: 'Total cash divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['cash per share', 'liquid assets per share', '每股现金', '每股现金资产'],
    unit: 'USD',
  },
  {
    field: 'bookValuePerShare',
    displayName: 'Book Value Per Share',
    description: 'Shareholders equity divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['book value per share', 'BVPS', 'net worth per share', '每股账面价值', '每股净资产'],
    unit: 'USD',
  },
  {
    field: 'tangibleBookValuePerShare',
    displayName: 'Tangible Book Value Per Share',
    description: 'Tangible assets minus liabilities divided by shares',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['tangible book value', 'TBVPS', 'tangible assets per share', '每股有形账面价值'],
    unit: 'USD',
  },
  {
    field: 'shareholdersEquityPerShare',
    displayName: 'Equity Per Share',
    description: 'Total shareholders equity divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['equity per share', 'shareholders equity', 'net worth', '每股股东权益'],
    unit: 'USD',
  },
  {
    field: 'operatingCashFlowPerShare',
    displayName: 'Operating Cash Flow Per Share',
    description: 'Operating cash flow divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['OCF per share', 'operating cash per share', '每股运营现金流'],
    unit: 'USD',
  },
  {
    field: 'capexPerShare',
    displayName: 'CapEx Per Share',
    description: 'Capital expenditures divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['capex per share', 'capital spending per share', '每股资本支出'],
    unit: 'USD',
  },
  {
    field: 'freeCashFlowPerShare',
    displayName: 'Free Cash Flow Per Share',
    description: 'Free cash flow divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['FCF per share', 'free cash per share', '每股自由现金流'],
    unit: 'USD',
  },
  {
    field: 'dividendPerShare',
    displayName: 'Dividend Per Share',
    description: 'Total dividends paid divided by shares outstanding',
    category: 'Per Share Metrics',
    tool: 'getFinancialRatios',
    keywords: ['DPS', 'dividend per share', 'dividend payment', '每股股息', '每股分红'],
    unit: 'USD',
  },

  // Other Ratios
  {
    field: 'solvencyRatio',
    displayName: 'Solvency Ratio',
    description: 'Net income plus depreciation divided by total liabilities',
    category: 'Solvency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['solvency', 'financial stability', 'debt coverage', '偿债能力比率'],
    isRatio: true,
  },
  {
    field: 'workingCapitalTurnoverRatio',
    displayName: 'Working Capital Turnover',
    description: 'Revenue divided by average working capital',
    category: 'Efficiency Ratios',
    tool: 'getFinancialRatios',
    keywords: ['working capital turnover', 'capital efficiency', '营运资金周转率'],
    isRatio: true,
  },
  {
    field: 'netIncomePerEBT',
    displayName: 'Net Income to EBT',
    description: 'Net income divided by earnings before tax',
    category: 'Tax Efficiency',
    tool: 'getFinancialRatios',
    keywords: ['tax efficiency', 'net income ratio', 'tax impact', '净利润税前比率'],
    isRatio: true,
  },
  {
    field: 'ebtPerEbit',
    displayName: 'EBT to EBIT',
    description: 'Earnings before tax divided by EBIT',
    category: 'Interest Efficiency',
    tool: 'getFinancialRatios',
    keywords: ['interest impact', 'EBT EBIT ratio', '税前利润息前比率'],
    isRatio: true,
  },
  {
    field: 'effectiveTaxRate',
    displayName: 'Effective Tax Rate',
    description: 'Income tax expense divided by pre-tax income',
    category: 'Tax Efficiency',
    tool: 'getFinancialRatios',
    keywords: ['tax rate', 'effective tax', 'tax burden', '实际税率', '有效税率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'debtToMarketCap',
    displayName: 'Debt to Market Cap',
    description: 'Total debt divided by market capitalization',
    category: 'Leverage Ratios',
    tool: 'getFinancialRatios',
    keywords: ['debt to market', 'market leverage', '债务市值比'],
    isRatio: true,
    isPercentage: true,
  },

  // Additional metadata fields (non-ratio)
  {
    field: 'symbol',
    displayName: 'Stock Symbol',
    description: 'Stock ticker symbol',
    category: 'Identifiers',
    tool: 'getFinancialRatios',
    keywords: ['ticker', 'symbol', 'stock code', '股票代码'],
  },
  {
    field: 'date',
    displayName: 'Report Date',
    description: 'Date of the financial report',
    category: 'Time Period',
    tool: 'getFinancialRatios',
    keywords: ['date', 'report date', 'period end', '报告日期'],
  },
  {
    field: 'fiscalYear',
    displayName: 'Fiscal Year',
    description: 'Fiscal year of the report',
    category: 'Time Period',
    tool: 'getFinancialRatios',
    keywords: ['fiscal year', 'FY', 'year', '财年'],
  },
  {
    field: 'period',
    displayName: 'Period',
    description: 'Reporting period (FY, Q1, Q2, Q3, Q4)',
    category: 'Time Period',
    tool: 'getFinancialRatios',
    keywords: ['period', 'quarter', 'annual', '期间', '季度'],
  },
  {
    field: 'reportedCurrency',
    displayName: 'Currency',
    description: 'Currency used in the report',
    category: 'Currency',
    tool: 'getFinancialRatios',
    keywords: ['currency', 'reporting currency', '货币', '币种'],
  },
];