export interface KeyMetricField {
  field: string;
  displayName: string;
  description: string;
  category: string;
  tool: string;
  keywords: string[];
  unit?: string;
  isRatio?: boolean;
  isPercentage?: boolean;
}

export const keyMetricsFields: KeyMetricField[] = [
  // Valuation Metrics
  {
    field: 'marketCap',
    displayName: 'Market Capitalization',
    description: 'Total market value of all outstanding shares',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['market cap', 'market capitalization', 'market value', 'shares outstanding', '市值', '市场价值'],
    unit: 'USD',
  },
  {
    field: 'enterpriseValue',
    displayName: 'Enterprise Value',
    description: 'Market cap plus debt minus cash, representing total company value',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['enterprise value', 'EV', 'total value', 'company value', '企业价值'],
    unit: 'USD',
  },
  {
    field: 'evToSales',
    displayName: 'EV/Sales',
    description: 'Enterprise value divided by revenue',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['EV sales', 'enterprise value sales', 'revenue multiple', 'EV/Sales'],
    isRatio: true,
  },
  {
    field: 'evToOperatingCashFlow',
    displayName: 'EV/Operating Cash Flow',
    description: 'Enterprise value divided by operating cash flow',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['EV OCF', 'cash flow multiple', 'operating cash flow valuation'],
    isRatio: true,
  },
  {
    field: 'evToFreeCashFlow',
    displayName: 'EV/Free Cash Flow',
    description: 'Enterprise value divided by free cash flow',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['EV FCF', 'free cash flow multiple', 'FCF valuation'],
    isRatio: true,
  },
  {
    field: 'evToEBITDA',
    displayName: 'EV/EBITDA',
    description: 'Enterprise value divided by EBITDA',
    category: 'Valuation Metrics',
    tool: 'getKeyMetrics',
    keywords: ['EV EBITDA', 'EBITDA multiple', 'earnings multiple', 'EV/EBITDA'],
    isRatio: true,
  },

  // Return Metrics
  {
    field: 'returnOnAssets',
    displayName: 'Return on Assets (ROA)',
    description: 'Net income divided by total assets, measuring asset efficiency',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['ROA', 'return on assets', 'asset efficiency', 'asset returns', '资产回报率', '总资产收益率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'operatingReturnOnAssets',
    displayName: 'Operating ROA',
    description: 'Operating income divided by total assets',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['operating ROA', 'operating return on assets', 'operational efficiency'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'returnOnTangibleAssets',
    displayName: 'Return on Tangible Assets',
    description: 'Net income divided by tangible assets',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['tangible assets return', 'ROTA', 'tangible asset efficiency'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'returnOnEquity',
    displayName: 'Return on Equity (ROE)',
    description: 'Net income divided by shareholders equity, measuring shareholder returns',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['ROE', 'return on equity', 'shareholder returns', 'equity efficiency', '净资产收益率', '股东回报率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'returnOnInvestedCapital',
    displayName: 'Return on Invested Capital (ROIC)',
    description: 'Operating profit after tax divided by invested capital',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['ROIC', 'return on invested capital', 'capital efficiency', 'investment returns'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'returnOnCapitalEmployed',
    displayName: 'Return on Capital Employed (ROCE)',
    description: 'EBIT divided by capital employed',
    category: 'Return Metrics',
    tool: 'getKeyMetrics',
    keywords: ['ROCE', 'capital employed', 'capital efficiency', 'employed capital returns'],
    isRatio: true,
    isPercentage: true,
  },

  // Cash Flow Metrics
  {
    field: 'freeCashFlowYield',
    displayName: 'Free Cash Flow Yield',
    description: 'Free cash flow per share divided by stock price',
    category: 'Cash Flow Metrics',
    tool: 'getKeyMetrics',
    keywords: ['FCF yield', 'free cash flow yield', 'cash yield', 'FCF return', '自由现金流收益率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'earningsYield',
    displayName: 'Earnings Yield',
    description: 'Earnings per share divided by stock price (inverse of P/E)',
    category: 'Cash Flow Metrics',
    tool: 'getKeyMetrics',
    keywords: ['earnings yield', 'earning yield', 'inverse PE', 'earning return', '盈利收益率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'freeCashFlowToEquity',
    displayName: 'Free Cash Flow to Equity',
    description: 'Cash flow available to equity holders after debt payments',
    category: 'Cash Flow Metrics',
    tool: 'getKeyMetrics',
    keywords: ['FCFE', 'equity cash flow', 'shareholder cash flow', '股东自由现金流'],
    unit: 'USD',
  },
  {
    field: 'freeCashFlowToFirm',
    displayName: 'Free Cash Flow to Firm',
    description: 'Cash flow available to all capital providers',
    category: 'Cash Flow Metrics',
    tool: 'getKeyMetrics',
    keywords: ['FCFF', 'firm cash flow', 'company cash flow', '企业自由现金流'],
    unit: 'USD',
  },

  // Capital Efficiency Metrics
  {
    field: 'capexToOperatingCashFlow',
    displayName: 'CapEx/Operating Cash Flow',
    description: 'Capital expenditures as percentage of operating cash flow',
    category: 'Capital Efficiency',
    tool: 'getKeyMetrics',
    keywords: ['capex ratio', 'capital spending', 'investment intensity', '资本支出比率'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'capexToDepreciation',
    displayName: 'CapEx/Depreciation',
    description: 'Capital expenditures divided by depreciation',
    category: 'Capital Efficiency',
    tool: 'getKeyMetrics',
    keywords: ['capex depreciation', 'asset replacement', 'maintenance capex'],
    isRatio: true,
  },
  {
    field: 'capexToRevenue',
    displayName: 'CapEx/Revenue',
    description: 'Capital expenditures as percentage of revenue',
    category: 'Capital Efficiency',
    tool: 'getKeyMetrics',
    keywords: ['capital intensity', 'capex sales ratio', 'investment revenue ratio'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'investedCapital',
    displayName: 'Invested Capital',
    description: 'Total capital invested in the business operations',
    category: 'Capital Efficiency',
    tool: 'getKeyMetrics',
    keywords: ['invested capital', 'capital invested', 'total capital', '投入资本'],
    unit: 'USD',
  },

  // Working Capital Metrics
  {
    field: 'workingCapital',
    displayName: 'Working Capital',
    description: 'Current assets minus current liabilities',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['working capital', 'net working capital', 'liquidity', 'short term assets', '营运资金', '运营资本'],
    unit: 'USD',
  },
  {
    field: 'currentRatio',
    displayName: 'Current Ratio',
    description: 'Current assets divided by current liabilities',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['current ratio', 'liquidity ratio', 'short term liquidity', '流动比率'],
    isRatio: true,
  },
  {
    field: 'daysOfSalesOutstanding',
    displayName: 'Days Sales Outstanding',
    description: 'Average days to collect receivables',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['DSO', 'days sales outstanding', 'receivables days', 'collection period', '应收账款周转天数'],
    unit: 'days',
  },
  {
    field: 'daysOfPayablesOutstanding',
    displayName: 'Days Payables Outstanding',
    description: 'Average days to pay suppliers',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['DPO', 'days payables outstanding', 'payment days', 'payables period', '应付账款周转天数'],
    unit: 'days',
  },
  {
    field: 'daysOfInventoryOutstanding',
    displayName: 'Days Inventory Outstanding',
    description: 'Average days to sell inventory',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['DIO', 'inventory days', 'days inventory', 'inventory period', '存货周转天数'],
    unit: 'days',
  },
  {
    field: 'operatingCycle',
    displayName: 'Operating Cycle',
    description: 'DSO plus DIO, time to convert inventory to cash',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['operating cycle', 'cash cycle', 'business cycle', '营业周期'],
    unit: 'days',
  },
  {
    field: 'cashConversionCycle',
    displayName: 'Cash Conversion Cycle',
    description: 'Operating cycle minus DPO, net time to generate cash',
    category: 'Working Capital',
    tool: 'getKeyMetrics',
    keywords: ['cash conversion cycle', 'CCC', 'cash cycle', 'working capital cycle', '现金转换周期'],
    unit: 'days',
  },

  // Debt Metrics
  {
    field: 'netDebtToEBITDA',
    displayName: 'Net Debt/EBITDA',
    description: 'Net debt divided by EBITDA, measuring debt burden',
    category: 'Debt Metrics',
    tool: 'getKeyMetrics',
    keywords: ['debt EBITDA', 'leverage ratio', 'debt burden', 'net debt ratio', '净债务EBITDA比率'],
    isRatio: true,
  },
  {
    field: 'taxBurden',
    displayName: 'Tax Burden',
    description: 'Net income divided by pre-tax income',
    category: 'Debt Metrics',
    tool: 'getKeyMetrics',
    keywords: ['tax burden', 'tax impact', 'tax efficiency', '税负', '税收负担'],
    isRatio: true,
  },
  {
    field: 'interestBurden',
    displayName: 'Interest Burden',
    description: 'Pre-tax income divided by EBIT',
    category: 'Debt Metrics',
    tool: 'getKeyMetrics',
    keywords: ['interest burden', 'interest coverage', 'interest impact', '利息负担'],
    isRatio: true,
  },

  // Quality Metrics
  {
    field: 'incomeQuality',
    displayName: 'Income Quality',
    description: 'Operating cash flow divided by net income',
    category: 'Quality Metrics',
    tool: 'getKeyMetrics',
    keywords: ['income quality', 'earnings quality', 'cash quality', 'profit quality', '收益质量', '利润质量'],
    isRatio: true,
  },
  {
    field: 'grahamNumber',
    displayName: 'Graham Number',
    description: 'Fair value estimate using Benjamin Graham formula',
    category: 'Quality Metrics',
    tool: 'getKeyMetrics',
    keywords: ['graham number', 'fair value', 'intrinsic value', 'graham formula', '格雷厄姆数'],
    unit: 'USD',
  },
  {
    field: 'grahamNetNet',
    displayName: 'Graham Net-Net',
    description: 'Net current assets minus total liabilities',
    category: 'Quality Metrics',
    tool: 'getKeyMetrics',
    keywords: ['graham net net', 'net working capital', 'asset value', '格雷厄姆净网资产'],
    unit: 'USD',
  },

  // Revenue Breakdown
  {
    field: 'researchAndDevelopementToRevenue',
    displayName: 'R&D/Revenue',
    description: 'Research and development expenses as percentage of revenue',
    category: 'Revenue Breakdown',
    tool: 'getKeyMetrics',
    keywords: ['R&D ratio', 'research development', 'innovation spending', 'RD revenue', '研发占收入比'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'stockBasedCompensationToRevenue',
    displayName: 'Stock Compensation/Revenue',
    description: 'Stock-based compensation as percentage of revenue',
    category: 'Revenue Breakdown',
    tool: 'getKeyMetrics',
    keywords: ['stock compensation', 'equity compensation', 'stock options', 'SBC revenue', '股权激励占收入比'],
    isRatio: true,
    isPercentage: true,
  },
  {
    field: 'salesGeneralAndAdministrativeToRevenue',
    displayName: 'SG&A/Revenue',
    description: 'Selling, general and administrative expenses as percentage of revenue',
    category: 'Revenue Breakdown',
    tool: 'getKeyMetrics',
    keywords: ['SGA revenue', 'admin expenses', 'operating expenses ratio', 'SG&A ratio'],
    isRatio: true,
    isPercentage: true,
  },

  // Asset Metrics
  {
    field: 'tangibleAssetValue',
    displayName: 'Tangible Asset Value',
    description: 'Book value excluding intangible assets',
    category: 'Asset Metrics',
    tool: 'getKeyMetrics',
    keywords: ['tangible assets', 'book value', 'asset value', 'net tangible assets', '有形资产价值'],
    unit: 'USD',
  },
  {
    field: 'netCurrentAssetValue',
    displayName: 'Net Current Asset Value',
    description: 'Current assets minus total liabilities',
    category: 'Asset Metrics',
    tool: 'getKeyMetrics',
    keywords: ['net current assets', 'liquid asset value', 'working capital value', '净流动资产价值'],
    unit: 'USD',
  },
  {
    field: 'intangiblesToTotalAssets',
    displayName: 'Intangibles/Total Assets',
    description: 'Intangible assets as percentage of total assets',
    category: 'Asset Metrics',
    tool: 'getKeyMetrics',
    keywords: ['intangible assets', 'intangible ratio', 'asset composition', '无形资产比率'],
    isRatio: true,
    isPercentage: true,
  },

  // Average Balance Metrics
  {
    field: 'averageReceivables',
    displayName: 'Average Receivables',
    description: 'Average accounts receivable balance',
    category: 'Balance Metrics',
    tool: 'getKeyMetrics',
    keywords: ['average receivables', 'receivables balance', 'AR balance', '平均应收账款'],
    unit: 'USD',
  },
  {
    field: 'averagePayables',
    displayName: 'Average Payables',
    description: 'Average accounts payable balance',
    category: 'Balance Metrics',
    tool: 'getKeyMetrics',
    keywords: ['average payables', 'payables balance', 'AP balance', '平均应付账款'],
    unit: 'USD',
  },
  {
    field: 'averageInventory',
    displayName: 'Average Inventory',
    description: 'Average inventory balance',
    category: 'Balance Metrics',
    tool: 'getKeyMetrics',
    keywords: ['average inventory', 'inventory balance', 'stock balance', '平均库存'],
    unit: 'USD',
  },

  // Metadata fields
  {
    field: 'symbol',
    displayName: 'Stock Symbol',
    description: 'Stock ticker symbol',
    category: 'Identifiers',
    tool: 'getKeyMetrics',
    keywords: ['ticker', 'symbol', 'stock code', '股票代码'],
  },
  {
    field: 'date',
    displayName: 'Report Date',
    description: 'Date of the financial report',
    category: 'Time Period',
    tool: 'getKeyMetrics',
    keywords: ['date', 'report date', 'period end', '报告日期'],
  },
  {
    field: 'fiscalYear',
    displayName: 'Fiscal Year',
    description: 'Fiscal year of the report',
    category: 'Time Period',
    tool: 'getKeyMetrics',
    keywords: ['fiscal year', 'FY', 'year', '财年'],
  },
  {
    field: 'period',
    displayName: 'Period',
    description: 'Reporting period (FY, Q1, Q2, Q3, Q4)',
    category: 'Time Period',
    tool: 'getKeyMetrics',
    keywords: ['period', 'quarter', 'annual', '期间', '季度'],
  },
  {
    field: 'reportedCurrency',
    displayName: 'Currency',
    description: 'Currency used in the report',
    category: 'Currency',
    tool: 'getKeyMetrics',
    keywords: ['currency', 'reporting currency', '货币', '币种'],
  },
];