-- Migration: Create analysis_blocks table for storing financial analysis results
-- Created: 2025-10-01
-- Description: This table stores analysis blocks generated by AI agents, containing tables, charts, and insights

-- Create analysis_blocks table
CREATE TABLE IF NOT EXISTS analysis_blocks (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to chats table (direct relationship, no intermediate reports table)
  chat_id UUID NOT NULL REFERENCES chats(id) ON DELETE CASCADE,

  -- Core fields
  type VARCHAR(50) NOT NULL CHECK (type IN (
    'metric',       -- Single metric display
    'trend',        -- Trend analysis
    'comparison',   -- Comparison analysis
    'breakdown',    -- Decomposition analysis
    'ranking',      -- Ranking analysis
    'correlation',  -- Correlation analysis
    'forecast',     -- Forecast/prediction
    'summary'       -- Summary/overview
  )),
  title TEXT NOT NULL,
  order_index INTEGER NOT NULL DEFAULT 0,  -- Display order within the chat

  -- Flexible JSONB storage for all block content
  -- This allows us to evolve the schema without migrations
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  /*
  Example content structure:
  {
    "query": "Analyze AAPL ROCE",                    -- Original user query
    "data": {
      "table_file": "blocks/2024/12/block_xxx.parquet",  -- Reference to parquet file
      "chart_file": "blocks/2024/12/block_xxx.html",     -- Reference to chart HTML
      "image_file": "blocks/2024/12/block_xxx.png"       -- Reference to image file
    },
    "insights": [                                    -- Key insights (text)
      "ROCE is 15.2%, down 7.3% QoQ",
      "Below industry average by 3pp"
    ],
    "metrics": {                                     -- Key metrics (numbers)
      "roce": 0.152,
      "qoq_change": -0.073,
      "industry_avg": 0.182
    },
    "summary": "AAPL ROCE trending downward...",     -- Executive summary
    "view": {                                        -- View configuration
      "primary": "table",
      "available": ["table", "chart", "metrics"]
    },
    "suggestions": [                                 -- Follow-up suggestions
      {"label": "Break down ROCE", "action": "breakdown_roce"},
      {"label": "Compare with peers", "action": "compare_peers"}
    ],
    "metadata": {                                    -- Additional metadata
      "data_source": "MotherDuck",
      "execution_time_ms": 1234,
      "confidence": 0.95
    }
  }
  */

  -- Status tracking
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending',      -- Block created but not yet processed
    'generating',   -- Currently being generated
    'completed',    -- Successfully completed
    'error',        -- Generation failed
    'stale'         -- Data may be outdated
  )),

  -- Error tracking (only used when status = 'error')
  error_message TEXT,

  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX idx_analysis_blocks_chat_id_order
  ON analysis_blocks(chat_id, order_index);

CREATE INDEX idx_analysis_blocks_status
  ON analysis_blocks(status)
  WHERE status IN ('pending', 'generating');

CREATE INDEX idx_analysis_blocks_created_at
  ON analysis_blocks(created_at DESC);

-- Create index on JSONB content for specific queries (optional, can add more as needed)
CREATE INDEX idx_analysis_blocks_content_type
  ON analysis_blocks((content->>'type'));

-- Add trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_analysis_blocks_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_analysis_blocks_updated_at
  BEFORE UPDATE ON analysis_blocks
  FOR EACH ROW
  EXECUTE FUNCTION update_analysis_blocks_updated_at();

-- Add comments for documentation
COMMENT ON TABLE analysis_blocks IS 'Stores AI-generated analysis blocks containing tables, charts, and insights';
COMMENT ON COLUMN analysis_blocks.id IS 'Unique identifier for the analysis block';
COMMENT ON COLUMN analysis_blocks.chat_id IS 'Reference to the chat session this block belongs to';
COMMENT ON COLUMN analysis_blocks.type IS 'Type of analysis block (metric, trend, comparison, etc.)';
COMMENT ON COLUMN analysis_blocks.title IS 'Display title for the block';
COMMENT ON COLUMN analysis_blocks.order_index IS 'Display order within the chat (0-based)';
COMMENT ON COLUMN analysis_blocks.content IS 'Flexible JSONB storage for all block data, insights, and configuration';
COMMENT ON COLUMN analysis_blocks.status IS 'Current status of the block generation';
COMMENT ON COLUMN analysis_blocks.error_message IS 'Error details if generation failed';
COMMENT ON COLUMN analysis_blocks.created_at IS 'Timestamp when the block was created';
COMMENT ON COLUMN analysis_blocks.updated_at IS 'Timestamp when the block was last updated';